export interface Product {
  id: string;
  name: string;
  price: number;
  brand: string;
  category: string;
}

export const products: Product[] = [
  // CAPILAR - MILAGROS
  { id: "cap-1", name: "ACONDICIONADOR DE CEBOLLA MILAGROS X 450 ML", price: 36500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-2", name: "ACONDICIONADOR MILAGROS ARROZ Y LINAZA X 450 ML", price: 34500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-3", name: "ACONDICIONADOR MILAGROS HERBAL X 450 ML", price: 33500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-4", name: "ACONDICIONADOR ULTRANUTRITIVO PREMIUM MILAGROS X 450 ML", price: 35500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-5", name: "AMPOLLETA CAPILAR RESCATE INSTANTANEO MILAGROS X 30 ML", price: 13500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-6", name: "AMPOLLETA ELIXIR REVITALIZANTE MILAGROS X 30 ML", price: 14500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-7", name: "BARRA FIJADORA MILAGROS HAIR WAX X 49 G", price: 38000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-8", name: "BIOREPORALIZADOR MILAGROS X 450 L", price: 38000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-9", name: "CREMA HIDRATANTE MILAGROS ROJA X 1 L", price: 38000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-10", name: "CREMA HIDRATANTE MILAGROS ROSA X 1 L", price: 36000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-11", name: "MASCARILLA CAPILAR MULTIVITAMINICA MILAGROS X 450 ML", price: 37000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-12", name: "MASCARILLA CAPILAR REPARADORA DE CEBOLLA MILAGROS X 450ML", price: 39000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-13", name: "MASCARILLA MILAGROS HERBAL X 450 ML", price: 37000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-14", name: "PERFUME CAPILAR BALI MILAGROS X 120 ML", price: 36000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-15", name: "PERFUME CAPILAR GOLD MILAGROS X 120 ML", price: 36000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-16", name: "SHAMPOO DE CEBOLLA MILAGROS X 450 ML", price: 42000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-17", name: "SHAMPOO EMERGENCIA CAPILAR MILAGROS X 450 ML", price: 34500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-18", name: "SHAMPOO MAGIA CAPILAR MILAGROS X 450 ML", price: 35500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-19", name: "SHAMPOO ANTICASPA MILAGROS X 400 ML", price: 34000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-20", name: "SHAMPOO ARROZ Y ACIDO HIALURONICO MILAGROS X 450 ML", price: 34500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-21", name: "SHAMPOO HERBAL MILAGROS X 450 ML", price: 36500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-22", name: "SHAMPOO NATURAL FORTALECEDOR KIDS MILAGROS X 450 ML", price: 35500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-23", name: "SHAMPOO ULTRANUTRITIVO PREMIUM MILAGROS X 450 ML", price: 35500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-24", name: "TRATAMIENTO A BASE DE FRUTAS MILAGROS X 450 ML", price: 34500, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-25", name: "TRATAMIENTO DE PESTAÑAS MILAGROS X 6 ML", price: 46000, brand: "MILAGROS", category: "CAPILAR" },
  { id: "cap-26", name: "TRATAMIENTO EMERGENCIA CAPILAR MILAGROS X 450 ML", price: 34500, brand: "MILAGROS", category: "CAPILAR" },
  // CAPILAR - ANYELUZ
  { id: "cap-27", name: "ACONDICIONADOR ANYELUZ CON CEBOLLA X 500 ML", price: 40000, brand: "ANYELUZ", category: "CAPILAR" },
  { id: "cap-28", name: "ACONDICIONADOR ANYELUZ CON ROMERO X 500 ML", price: 40000, brand: "ANYELUZ", category: "CAPILAR" },
  { id: "cap-29", name: "SHAMPOO ANYELUZ CON ROMERO X 500 ML", price: 45000, brand: "ANYELUZ", category: "CAPILAR" },
  { id: "cap-30", name: "SHAMPOO ANYELUZ CON CEBOLLA, BIOTINA Y PROCAPIL X 500 ML", price: 42900, brand: "ANYELUZ", category: "CAPILAR" },
  // CAPILAR - POCION
  { id: "cap-31", name: "CREMA PARA PEINAR TONGOLE POCION X 450 ML", price: 37000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-32", name: "DUTONIC ANTICAIDA Y CRECIMIENTO POCION X 2", price: 60000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-33", name: "MASCARILLA ANCESTRAL PARA EL CABELLO POCION 350 ML", price: 42000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-34", name: "MASCARILLA BITE ME DE BANANO POCION 250 ML", price: 42000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-35", name: "MASCARILLA PARA RIZO TONGOLE POCION X 350 ML", price: 38000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-36", name: "OLEO CAPILAR BRILLO INFINITO POCION 30 ML", price: 49900, brand: "POCION", category: "CAPILAR" },
  { id: "cap-37", name: "SHAMPOO CONTROL GRASA POCION X 450 ML", price: 42000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-38", name: "SHAMPOO LA POCION KIDS POCION X 450 ML", price: 38000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-39", name: "SHAMPOO PARA RIZOS TONGOLE POCION X 450 ML", price: 41000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-40", name: "SHAMPOO REPARACION POCION X 450 ML", price: 41000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-41", name: "TERMOPROTECTOR BRILLO INFINITO POCION X 150 ML", price: 50900, brand: "POCION", category: "CAPILAR" },
  { id: "cap-42", name: "TRATAMIENTO ACONDICIONADOR RESTAURACION Y NUTRICION POCION X 450 ML", price: 40000, brand: "POCION", category: "CAPILAR" },
  { id: "cap-43", name: "TRATAMIENTO TONGOLE POCION X 450 ML", price: 40000, brand: "POCION", category: "CAPILAR" },
  // CAPILAR - ETNIKER
  { id: "cap-44", name: "CREMA PARA PEINAR ETNIKER X 500 GR", price: 58000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-45", name: "ESPUMA INTENSIFICADORA PARA RIZOS ETNIKER X 150 ML", price: 50000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-46", name: "GEL CURL DEFINNING ETNIKER X 1000 GR", price: 80000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-47", name: "GEL CURL DEFINNING ETNIKER X 300 GR", price: 26000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-48", name: "GEL FLUIDO ETNIKER X 300 ML", price: 40000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-49", name: "HYDROELIXIR OLEO CAPILAR ETNIKER X 38 ML", price: 34900, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-50", name: "MASCARILLA CONDITIONER ETNIKER X 300 GR", price: 38000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-51", name: "MASCARILLA CONDITIONER ETNIKER X 570 GR", price: 66000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-52", name: "REFRESCANTE DE RIZOS ETNIKER X 300 ML", price: 49900, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-53", name: "SHAMPOO LIMPIEZA PROFUNDA ETNIKER X 250 ML", price: 25900, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-54", name: "SHAMPOO NOURISHING ETNIKER X 250 ML", price: 36900, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-55", name: "SHAMPOO NOURISHING ETNIKER X 500 ML", price: 65000, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-56", name: "TRATAMIENTO AMAZONIA ETNIKER X 1000 GR", price: 48900, brand: "ETNIKER", category: "CAPILAR" },
  { id: "cap-57", name: "TRATAMIENTO CARIBE ETNIKER X 1000 GR", price: 48900, brand: "ETNIKER", category: "CAPILAR" },
  // CAPILAR - ORIGEN BOTANICO
  { id: "cap-58", name: "KERATINA ORIGEN BOTANICO X 1000 ML", price: 162000, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-59", name: "KERATINA ORIGEN BOTANICO X 120 ML", price: 37900, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-60", name: "KERATINA ORIGEN BOTANICO X 250 ML", price: 63000, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-61", name: "MASCARILLA BOMBA ORIGEN BOTANICO X 400 ML", price: 37000, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-62", name: "SHAMPOO ORIGEN BOTANICO X 400 ML", price: 34500, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-63", name: "TERMO PROTECTOR ORIGEN BOTANICO MINI X 2 UNID", price: 21000, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-64", name: "TERMO PROTECTOR ORIGEN BOTANICO SEDUCCION TENTACION X 120 ML", price: 24500, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  { id: "cap-65", name: "TRATAMIENTO ORIGEN BOTANICO X 400 ML", price: 36000, brand: "ORIGEN BOTANICO", category: "CAPILAR" },
  // CAPILAR - PROKPIL
  { id: "cap-66", name: "GEL FLUIDO PROKPIL X 300 ML", price: 25000, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-67", name: "TRATAMIENTO PROKPIL PLATINO X 300 ML", price: 33500, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-68", name: "TRATAMIENTO PROKPIL BEIGE X 150 ML", price: 20000, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-69", name: "TRATAMIENTO PROKPIL CENIZO X 150 ML", price: 20000, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-70", name: "TRATAMIENTO PROKPIL CHOCOLATE X 150 ML", price: 20000, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-71", name: "TRATAMIENTO PROKPIL PLATINO X 150 ML", price: 20000, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-72", name: "TRATAMIENTO PROKPIL ROJO X 150 ML", price: 20000, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-73", name: "TRATAMIENTO PROKPIL BEIGE X 300 ML", price: 33500, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-74", name: "TRATAMIENTO PROKPIL CENIZO X 300 ML", price: 33500, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-75", name: "TRATAMIENTO PROKPIL COBRE X 300 ML", price: 33500, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-76", name: "TRATAMIENTO PROKPIL COBRE DORADO X 300 ML", price: 33500, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-77", name: "TRATAMIENTO PROKPIL ROJO X 300 ML", price: 33500, brand: "PROKPIL", category: "CAPILAR" },
  { id: "cap-78", name: "TRATAMIENTO PROKPIL BLANCO POLAR X 350 G", price: 38200, brand: "PROKPIL", category: "CAPILAR" },
  // CAPILAR - SKALA
  { id: "cap-79", name: "TRATAMIENTO SKALA BABOSA X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-80", name: "TRATAMIENTO SKALA POTAO DO AMOR X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-81", name: "TRATAMIENTO SKALA DIVINO POTAO X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-82", name: "TRATAMIENTO SKALA DIVINO POTINHO KIDS X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-83", name: "TRATAMIENTO SKALA MAIONESE X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-84", name: "TRATAMIENTO SKALA MAIS CACHOS X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-85", name: "TRATAMIENTO SKALA MAIS CRESPOS X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  { id: "cap-86", name: "TRATAMIENTO SKALA MAIS LISOS X 1000 G", price: 29000, brand: "SKALA", category: "CAPILAR" },
  // CAPILAR - PONTO
  { id: "cap-87", name: "GEL BABY HAIR PONTO X 10 ML", price: 22800, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-88", name: "GEL CAPILAR GELLY FEST PONTO X 380 G", price: 25000, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-89", name: "GEL PONTO X 100 ML", price: 16000, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-90", name: "GEL RECUPERA TUS RIZOS PONTO", price: 39200, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-91", name: "SHAMPOO RECUPERA TUS RIZOS PONTO", price: 33000, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-92", name: "TRATAMIENTO BOMBA ANTI FRIZZ PONTO X 120 ML", price: 25600, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-93", name: "TRATAMIENTO BOMBA ANTI FRIZZ PONTO X 60 ML", price: 17200, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-94", name: "TRATAMIENTO MI DULCE PELO SOY LIZA 3 EN 1 X 380 G", price: 43500, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-95", name: "TRATAMIENTO MI DULCE PELO SOY ONDULADA 3 EN 1 X 380 G", price: 43500, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-96", name: "TRATAMIENTO 3 EN 1 HIDRATACION PONTO X 1000 G", price: 39900, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-97", name: "TRATAMIENTO 3 EN 1 NUTRICION PONTO X 1000 G", price: 39900, brand: "PONTO", category: "CAPILAR" },
  { id: "cap-98", name: "TRATAMIENTO 3 EN 1 REPARACION PONTO X 1000 G", price: 39900, brand: "PONTO", category: "CAPILAR" },
  // CAPILAR - CLICK HAIR
  { id: "cap-99", name: "ACONDICIONADOR 4 EN 1 CLICK HAIR X 300 ML", price: 44000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-100", name: "ACONDICIONADOR DE MIEL CLICK HAIR X 300 ML", price: 44000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-101", name: "MASCARILLA DE MIEL CLICK HAIR X 300 ML", price: 49900, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-102", name: "MIEL CAPILAR CLICK HAIR X 50 ML", price: 59000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-103", name: "PERFUME CAPILAR CLICK HAIR AMARILLO", price: 41000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-104", name: "PERFUME CAPILAR CLICK HAIR AZUL", price: 41000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-105", name: "PERFUME CAPILAR DE MIEL CLICK HAIR X 100 ML", price: 58000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-106", name: "PERFUME CAPILAR CLICK HAIR MORADO", price: 41000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-107", name: "PERFUME CAPILAR CLICK HAIR ROSADO", price: 41000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-108", name: "PERFUME CAPILAR CLICK HAIR VAINILLA GLOW", price: 41000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-109", name: "PERFUME CAPILAR DE MIEL Y MASMELO BRILLO INTENSO CLICK HAIR", price: 58000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-110", name: "SHAMPOO GRASO DE AJI CLICK HAIR X 300 ML", price: 44000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-111", name: "SHAMPOO MIEL CLICK HAIR X 300 ML", price: 44000, brand: "CLICK HAIR", category: "CAPILAR" },
  { id: "cap-112", name: "SUERO RECONSTRUCTOR CLICK HAIR X 120 ML", price: 38000, brand: "CLICK HAIR", category: "CAPILAR" },
  // CAPILAR - KARICIA
  { id: "cap-113", name: "SHAMPOO KARICIA CAPIXYL MEN X 400 ML", price: 26000, brand: "KARICIA", category: "CAPILAR" },
  { id: "cap-114", name: "SHAMPOO KARICIA CAPIXYL DAMA X 400 ML", price: 25600, brand: "KARICIA", category: "CAPILAR" },
  { id: "cap-115", name: "TRATAMIENTO KARICIA CAPIXYL X 400 ML", price: 28000, brand: "KARICIA", category: "CAPILAR" },

  // MAQUILLAJE - MONTOC
  { id: "maq-1", name: "BROCHA DE CEJAS ORGANICA MONTOC", price: 10000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-2", name: "BROW SET DE PALETAS DE CEJAS X 3 TONO LIGHT MONTOC", price: 26000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-3", name: "BROW SET DE PALETAS DE CEJAS X 3 TONO MEDIO MONTOC", price: 26000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-4", name: "COMFORT LIP OIL # 100 MONTOC", price: 28000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-5", name: "COMFORT LIP OIL # 200 MONTOC", price: 28000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-6", name: "COMFORT LIP OIL # 300 MONTOC", price: 28000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-7", name: "COMFORT LIP OIL # 400 MONTOC", price: 28000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-8", name: "DIXY FIX FIJADOR DE MAQUILLAJE MONTOC X 30 ML", price: 23000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-9", name: "HUMIDE LAPIZ DE CEJAS DOBLE MEDIUM MONTOC", price: 18000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-10", name: "ILUMINADOR INDIVIDUAL LIGTH SET 01 GOLDEN/ROSE/CHAMPAGNE MONTOC", price: 35000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-11", name: "LABIAL CORA LIP 02 CLARA MONTOC", price: 24900, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-12", name: "LABIAL CORA LIP 02 PECHICHE MONTOC", price: 24900, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-13", name: "LABIAL CORA LIP 02 TOXI MONTOC", price: 24900, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-14", name: "LABIAL CORA LIP 02 KISS MONTOC", price: 24900, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-15", name: "LIPPIE CHEEKS ANTO #400 MONTOC", price: 23000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-16", name: "LIPPIE CHEEKS ANTO #300 MONTOC", price: 23000, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-17", name: "BORLA CORAZON MONTOC", price: 4500, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-18", name: "RUBOR NOSTALGIC BLUSH DARLING-EXQUISITE-SO PRETTY MONTOC", price: 32200, brand: "MONTOC", category: "MAQUILLAJE" },
  { id: "maq-19", name: "RUBOR POCKET BLUSH MATIC-LEIDISY-SWEET MONTOC", price: 26000, brand: "MONTOC", category: "MAQUILLAJE" },
  // MAQUILLAJE - ANI-K
  { id: "maq-20", name: "BALSAMO LABIAL 01 ANI-K", price: 20000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-21", name: "BALSAMO LABIAL 02 ANI-K", price: 20000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-22", name: "BALSAMO LABIAL 03 ANI-K", price: 20000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-23", name: "BRILLO DE LABIOS LIP GLOSS 01 ANI-K", price: 21000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-24", name: "BRILLO DE LABIOS LIP GLOSS 02 ANI-K", price: 21000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-25", name: "CORRECTOR BASE 2 EN 1 BONITA 00 ANI-K", price: 42000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-26", name: "CORRECTOR BASE 2 EN 1 BONITA 02 ANI-K", price: 42000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-27", name: "CORRECTOR DE OJERAS 00 ANI-K", price: 24000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-28", name: "CORRECTOR DE OJERAS 01 ANI-K", price: 24000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-29", name: "CORRECTOR DE OJERAS 02 ANI-K", price: 24000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-30", name: "DELINEADOR DE LABIOS KISS DEFINITIO 01 ANI-K", price: 14000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-31", name: "DELINEADOR DE LABIOS KISS DEFINITIO 02 ANI-K", price: 14000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-32", name: "DELINEADOR DE LABIOS KISS DEFINITIO 03 ANI-K", price: 14000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-33", name: "DELINEADOR LIQUIDO NIGHT ANI-K", price: 12000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-34", name: "ILUMINADOR SUELTO 01 ANI-K", price: 22000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-35", name: "ILUMINADOR CREAM HIGHLIGHTER 01 ANI-K", price: 34000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-36", name: "ILUMINADOR CREAM HIGHLIGHTER 02 ANI-K", price: 34000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-37", name: "ILUMINADOR HIGHLIGHTER 01 ANI-K", price: 25000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-38", name: "ILUMINADOR HIGHLIGHTER 02 ANI-K", price: 25000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-39", name: "KIT DE CEJAS BROWN HARMONY 02 ANI-K", price: 23000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-40", name: "KIT DE CEJAS BROWN HARMONY 03 ANI-K", price: 23000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-41", name: "LAPIZ DE CEJAS 02 ANI-K", price: 16000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-42", name: "LAPIZ DE CEJAS 03 ANI-K", price: 16000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-43", name: "PESTAÑINA FLASH LASH ANI-K", price: 24000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-44", name: "RUBOR BLUSH 01 ANI-K", price: 20000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-45", name: "RUBOR BLUSH 02 ANI-K", price: 20000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-46", name: "RUBOR BLUSH 03 ANI-K", price: 20000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-47", name: "RUBOR LIQUIDO 01 ANI-K", price: 28000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-48", name: "RUBOR LIQUIDO 02 ANI-K", price: 28000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-49", name: "RUBOR LIQUIDO 03 ANI-K", price: 28000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-50", name: "RUBOR MINERALIZE 03 ANI-K", price: 24000, brand: "ANI-K", category: "MAQUILLAJE" },
  { id: "maq-51", name: "RUBOR MINERALIZE 04 ANI-K", price: 24000, brand: "ANI-K", category: "MAQUILLAJE" },
  // MAQUILLAJE - BLOOMSHELL
  { id: "maq-52", name: "BASE 2 EN 1 BLOOMSHELL TONO 01", price: 29800, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-53", name: "BASE 2 EN 1 BLOOMSHELL TONO 4,2", price: 29800, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-54", name: "BASE 2 EN 1 BLOOMSHELL TONO 4,5", price: 29800, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-55", name: "BASE 2 EN 1 BLOOMSHELL TONO 4,8", price: 29800, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-56", name: "BLOOM PUFF PRIMER BLOOMSHELL", price: 18500, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-57", name: "DUO LLAVERO BRILLO BLOOMSHELL", price: 25000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-58", name: "ILUMINADOR BLOOM GLOW CHARLOTTE BLOOMSHELL", price: 27000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-59", name: "ILUMINADOR BLOOM GLOW SACHA BLOOMSHELL", price: 27000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-60", name: "ILUMINADOR BLOOM GLOW ANTONELLA BLOOMSHELL", price: 27000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-61", name: "KIT BROCHAS BLOOM PETITE KBM70 BLOOMSHELL", price: 23600, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-62", name: "LLAVERO DUO BRILLO LABIAL BLOOMSHELL", price: 26800, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-63", name: "POLVO COMPACTO 4 TONOS BLOOMSHELL", price: 28900, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-64", name: "POLVO SUELTO 4 TONOS BLOOMSHELL", price: 29900, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-65", name: "RUBOR X 3 VELVET CRUSH 01 BLOOMSHELL", price: 36000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-66", name: "RUBOR X 3 VELVET CRUSH 02 BLOOMSHELL", price: 36000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-67", name: "RUBOR X 3 VELVET CRUSH 03 BLOOMSHELL", price: 36000, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  { id: "maq-68", name: "TINTA LABIOS LLAVERO BLOOMSHELL", price: 16500, brand: "BLOOMSHELL", category: "MAQUILLAJE" },
  // MAQUILLAJE - ATENEA
  { id: "maq-69", name: "ACONDICIONADOR REPARADOR DE LABIOS ATENEA", price: 36000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-70", name: "CORRECTOR LIQUIDO 1ST SCENE BEIGE ATENEA", price: 44900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-71", name: "CORRECTOR LIQUIDO 1ST SCENE VAINILLA ATENEA", price: 44900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-72", name: "CORRECTOR LIQUIDO 1ST SCENE NEUTRALIZER ATENEA", price: 44900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-73", name: "LABIAL LIQUIDO VELVETOUCH ATENEA", price: 23900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-74", name: "LIP BALM CHERRY ATENEA", price: 28000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-75", name: "LIP GLOSS 1ST SCENE BRIGHT PINK ATENEA", price: 40000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-76", name: "LIP GLOSS 1ST SCENE COCO ATENEA", price: 40000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-77", name: "LIP GLOSS 1ST SCENE CORAL ATENEA", price: 40000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-78", name: "LIP OIL SOFT RED ATENEA", price: 32000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-79", name: "LIP OIL TINTED GIRL BOSS ATENEA", price: 32000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-80", name: "LIP OIL TINTED SASSY ATENEA", price: 32000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-81", name: "LIP OIL TINTED SELF LOVE ATENEA", price: 32000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-82", name: "LIP OIL TINTED SPICY ATENEA", price: 32000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-83", name: "MINI BASE 1ST SCENE 01 LIGHT ATENEA X 30 ML", price: 45900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-84", name: "MINI BASE 1ST SCENE 03 LIGHT ATENEA X 30 ML", price: 45900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-85", name: "MINI BASE 1ST SCENE 04 LIGHT ATENEA X 30 ML", price: 45900, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-86", name: "PEPTIDE LIP BALM COOL MINT ATENEA X 15 ML", price: 37000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-87", name: "PEPTIDE LIP BALM CHERRY SPARK ATENEA X 15 ML", price: 37000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-88", name: "PEPTIDE LIP BALM CHOCOLATE ATENEA X 15 ML", price: 37000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-89", name: "PEPTIDE LIP BALM PINK SUGAR ATENEA X 15 ML", price: 37000, brand: "ATENEA", category: "MAQUILLAJE" },
  { id: "maq-90", name: "PESTAÑAS FOCUS DARLING 3D ATENEA", price: 9500, brand: "ATENEA", category: "MAQUILLAJE" },
  // MAQUILLAJE - SAMY
  { id: "maq-91", name: "BALSAMO PARA LABIOS PEPTIDE SAMY", price: 15500, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-92", name: "BASE SKIN MIRACLE X 30 G SAMY", price: 13000, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-93", name: "BB CREAM X 30 ML SAMY", price: 18200, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-94", name: "CORRECTOR CREMOSO 01 SAMY", price: 9800, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-95", name: "CORRECTOR CREMOSO 02 SAMY", price: 9800, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-96", name: "CORRECTOR CREMOSO 03 SAMY", price: 9800, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-97", name: "CORRECTOR CREMOSO 04 SAMY", price: 9800, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-98", name: "CORRECTOR CREMOSO 05 SAMY", price: 9800, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-99", name: "CORRECTOR CREMOSO 06 SAMY", price: 9800, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-100", name: "CORRECTOR LIQUID CONCELEAR SAMY", price: 17900, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-101", name: "ILUMINADOR COMPACTO SUNSET GLAM 01 SAMY", price: 18000, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-102", name: "ILUMINADOR COMPACTO SUNSET GLAM 02 SAMY", price: 18000, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-103", name: "ILUMINADOR COMPACTO SUNSET GLAM 03 SAMY", price: 18000, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-104", name: "LABIAL RETRACTIL MATE CREMOSO SAMY", price: 19900, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-105", name: "LAPIZ RETRACTIL PARA CEJAS SAMY", price: 29700, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-106", name: "PAPEL ANTIBRILLO SAMY", price: 11200, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-107", name: "PESTAÑINA SAMY ICONIC/CURL/LEGHT/VOLUME", price: 23500, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-108", name: "RUBOR COMPACTO BAKED BLUSH VELVET 04 SAMY", price: 26000, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-109", name: "RUBOR COMPACTO BAKED BLUSH VELVET 02 SAMY", price: 26000, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-110", name: "RUBOR CREMA Y POLVO SUNSET GLAM CANDY DREAM SAMY", price: 27500, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-111", name: "RUBOR INDIVIDUAL MINERAL SIN ESPEJO SAMY", price: 9500, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-112", name: "SERUM HIDRATANTE X 30 ML SAMY", price: 29900, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-113", name: "SERUM NUTRITIVO X 30 ML SAMY", price: 29900, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-114", name: "SERUM REPARADOR X 30 ML SAMY", price: 29900, brand: "SAMY", category: "MAQUILLAJE" },
  { id: "maq-115", name: "TINTA PARA LABIOS SAMY", price: 15900, brand: "SAMY", category: "MAQUILLAJE" },
  // MAQUILLAJE - RUBY ROSE
  { id: "maq-116", name: "BALSAMO PARA LABIOS LLAVERO CHERRY 02 RUBY ROSE", price: 18000, brand: "RUBY ROSE", category: "MAQUILLAJE" },
  { id: "maq-117", name: "GEL PARA CEJAS MELU RUBY ROSE", price: 17000, brand: "RUBY ROSE", category: "MAQUILLAJE" },
  { id: "maq-118", name: "LIP OIL GLOSS RUBY ROSE X 3,8 ML", price: 13000, brand: "RUBY ROSE", category: "MAQUILLAJE" },
  // MAQUILLAJE - ANYELUZ
  { id: "maq-119", name: "TINTA PARA LABIOS ANYELUZ 6,7 ML", price: 15500, brand: "ANYELUZ", category: "MAQUILLAJE" },

  // CORPORAL - LACTOVIT
  { id: "corp-1", name: "GEL DE BAÑO REPARADOR LACTOUREA X 300 ML", price: 20200, brand: "LACTOVIT", category: "CORPORAL" },
  { id: "corp-2", name: "GEL DE BAÑO REPARADOR LACTOUREA X 600 ML", price: 30600, brand: "LACTOVIT", category: "CORPORAL" },
  { id: "corp-3", name: "LECHE CORPORAL LACTOVIT REPARADOR X 1000 ML", price: 55000, brand: "LACTOVIT", category: "CORPORAL" },
  { id: "corp-4", name: "LECHE CORPORAL LACTOVIT REPARADOR X 250 ML", price: 24800, brand: "LACTOVIT", category: "CORPORAL" },
  { id: "corp-5", name: "LECHE CORPORAL LACTOVIT REPARADOR X 400 ML", price: 34900, brand: "LACTOVIT", category: "CORPORAL" },
  // CORPORAL - LUBRIDERM
  { id: "corp-6", name: "CREMA LUBRIDERM MEN FRAGANCIA X 400 ML", price: 50000, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-7", name: "CREMA LUBRIDERM HUMECTACION DIARIA X 400 ML", price: 38800, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-8", name: "CREMA LUBRIDERM REPARACION INTENSIVA X 400 ML", price: 41000, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-9", name: "CREMA LUBRIDERM UV-15 X 400 ML", price: 46600, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-10", name: "CREMA LUBRIDERM HUMECTACION DIARIA X 946 ML", price: 64000, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-11", name: "CREMA LUBRIDERM REPARACION INTENSIVA X 946 ML", price: 79600, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-12", name: "CREMA LUBRIDERM UV-15 X 946 ML", price: 75000, brand: "LUBRIDERM", category: "CORPORAL" },
  { id: "corp-13", name: "DECOLORANTE RAYITOS DE SOL", price: 16000, brand: "LUBRIDERM", category: "CORPORAL" },
  // CORPORAL - LLUVIA DE ESTRELLAS
  { id: "corp-14", name: "BABY CREAM LLUVIA DE ESTRELLAS X 150 ML", price: 18900, brand: "LLUVIA DE ESTRELLAS", category: "CORPORAL" },
  { id: "corp-15", name: "ILUMINADOR CORPORAL ROSADO/MORADO/AMARILLO LLUVIA DE ESTRELLAS", price: 25000, brand: "LLUVIA DE ESTRELLAS", category: "CORPORAL" },
  { id: "corp-16", name: "MANTEQUILLA CORPORAL DE CANELA X 200 ML LLUVIA DE ESTRELLAS", price: 37900, brand: "LLUVIA DE ESTRELLAS", category: "CORPORAL" },
  // CORPORAL - BABARIA
  { id: "corp-17", name: "ESPUMA PARA RIZOS X 250 ML BABARIA", price: 32200, brand: "BABARIA", category: "CORPORAL" },
  { id: "corp-18", name: "GEL DE BAÑO DE ALMENDRAS X 600 ML BABARIA", price: 21900, brand: "BABARIA", category: "CORPORAL" },
  { id: "corp-19", name: "GEL DE BAÑO DE AVENA X 600 ML BABARIA", price: 21900, brand: "BABARIA", category: "CORPORAL" },
  { id: "corp-20", name: "GEL DE BAÑO DE ALOE X 600 ML BABARIA", price: 23900, brand: "BABARIA", category: "CORPORAL" },
  { id: "corp-21", name: "JABON INTIMO ROSA MOSQUETA X 300 ML BABARIA", price: 21000, brand: "BABARIA", category: "CORPORAL" },
  { id: "corp-22", name: "JABON INTIMO ALOE X 300 ML BABARIA", price: 21000, brand: "BABARIA", category: "CORPORAL" },
  // CORPORAL - NIVEA
  { id: "corp-23", name: "AGUA MICELAR AGUA DE ROSAS X 400 ML NIVEA", price: 32000, brand: "NIVEA", category: "CORPORAL" },
  { id: "corp-24", name: "AGUA MICELAR ILUMINADORA X 400 ML NIVEA", price: 34900, brand: "NIVEA", category: "CORPORAL" },
  { id: "corp-25", name: "BLOQUEADOR NIVEA X 50 FPS50 ANTIEDAD Q10", price: 48500, brand: "NIVEA", category: "CORPORAL" },
  { id: "corp-26", name: "CREMA CORPORAL MILK NUTRITIVA X 625 ML NIVEA", price: 40000, brand: "NIVEA", category: "CORPORAL" },
  // CORPORAL - NUDE
  { id: "corp-27", name: "PROTECTOR SOLAR FACIAL NUDE CON COLOR FSP50 X 50 ML", price: 54000, brand: "NUDE", category: "CORPORAL" },
  { id: "corp-28", name: "PROTECTOR SOLAR FACIAL NUDE FLUIDO CON COLOR FSP60 X 50 ML", price: 52000, brand: "NUDE", category: "CORPORAL" },
  { id: "corp-29", name: "PROTECTOR SOLAR FACIAL NUDE FLUIDO SIN COLOR FSP60 X 50 ML", price: 55000, brand: "NUDE", category: "CORPORAL" },
  { id: "corp-30", name: "PROTECTOR SOLAR CARA Y CUERPO FSP60 X 40 ML", price: 23000, brand: "NUDE", category: "CORPORAL" },
  { id: "corp-31", name: "BRONCEADOR EN ACEITE NUDE X 240 ML", price: 37200, brand: "NUDE", category: "CORPORAL" },
  // CORPORAL - KARICIA
  { id: "corp-32", name: "RITUAL DE NOVIA KARICIA", price: 11600, brand: "KARICIA", category: "CORPORAL" },

  // TINTES
  { id: "tint-1", name: "TINTURA WELLA PERFECT COLOR", price: 26500, brand: "WELLA", category: "TINTES" },
  { id: "tint-2", name: "TINTURA PERMANENTE IGORA ROYAL 60 ML", price: 24500, brand: "IGORA", category: "TINTES" },
  { id: "tint-3", name: "TINTURA NOUVELLE", price: 26000, brand: "NOUVELLE", category: "TINTES" },
  { id: "tint-4", name: "TINTURA TOUCH NOUVELLE", price: 21500, brand: "NOUVELLE", category: "TINTES" },
  { id: "tint-5", name: "TINTURA DUVY CLASS", price: 15000, brand: "DUVY CLASS", category: "TINTES" },
  { id: "tint-6", name: "TINTURA DUVY CLASS (COLORES FANTASIA)", price: 19000, brand: "DUVY CLASS", category: "TINTES" },
  { id: "tint-7", name: "TINTURA IGORA VITAL", price: 19500, brand: "IGORA", category: "TINTES" },
  { id: "tint-8", name: "TINTURA PALETTE", price: 14400, brand: "PALETTE", category: "TINTES" },
  { id: "tint-9", name: "TINTURA ROJO SHANGAI SALERM", price: 27000, brand: "SALERM", category: "TINTES" },
  { id: "tint-10", name: "TINTURA THYMS", price: 17000, brand: "THYMS", category: "TINTES" },
  { id: "tint-11", name: "TINTURA SALOONIN RECAMIER", price: 26000, brand: "RECAMIER", category: "TINTES" },
  { id: "tint-12", name: "TINTURA EOC ALFAPARF", price: 27000, brand: "ALFAPARF", category: "TINTES" },
  { id: "tint-13", name: "TINTURA EOC PLATINUM ALFAPARF", price: 27000, brand: "ALFAPARF", category: "TINTES" },
  { id: "tint-14", name: "TINTURA REVOLUTION ALFAPARF", price: 23000, brand: "ALFAPARF", category: "TINTES" },

  // ACCESORIOS
  { id: "acc-1", name: "PLANCHA RADIANCE COSMOS", price: 210000, brand: "COSMOS", category: "ACCESORIOS" },
  { id: "acc-2", name: "PLANCHA COSMOS FENIX", price: 240000, brand: "COSMOS", category: "ACCESORIOS" },
  { id: "acc-3", name: "SECADOR COSMOS FENIX 2200 W", price: 197900, brand: "COSMOS", category: "ACCESORIOS" },
  { id: "acc-4", name: "SECADOR SADIRA 2200W COSMOS", price: 199000, brand: "COSMOS", category: "ACCESORIOS" },
  { id: "acc-5", name: "LAMPARA LED SUN T2 PLUS", price: 115000, brand: "SUN", category: "ACCESORIOS" },
  { id: "acc-6", name: "LAMPARA LED SUN H9 PLUS", price: 121000, brand: "SUN", category: "ACCESORIOS" },
];

export const categories = ["CAPILAR", "MAQUILLAJE", "CORPORAL", "TINTES", "ACCESORIOS"] as const;

export const getBrandsByCategory = (category: string): string[] => {
  const brands = new Set<string>();
  products.filter(p => p.category === category).forEach(p => brands.add(p.brand));
  return Array.from(brands);
};

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    minimumFractionDigits: 0,
  }).format(price);
};
